application:
    image: debian:jessie
    volumes:
        - ./project/application:/var/www/ng-app
    tty: true

nodejs:
    build: docker/nodejs
    restart: always
    container_name: ng-app_nodejs
    volumes_from:
        - application
    stdin_open: true
    tty: true

nginx:
    build: docker/nginx
    restart: always
    volumes_from:
        - application
